### PR TITLE
Bug Fixes and Better Error messages

### PR DESCRIPTION
**Pull request by SerCoach1**
+ Added Console window close event handler (tries to close all processes before exiting)
+ Fixed bug where an exception was thrown when you input a directory that does not contain UnitConverterWebApp
+ Added more detailed error messages (related to dotCover, dupFinder and appsettings)
+ Fixed bug #125

### CODE REVIEW

**Comment by jogobom** [comment]
Am I right in thinking that the purpose of `ConsoleCloseHandler` is to ensure that when somebody terminates YoCode it _always_ closes all the child processes that it started? I haven't tested to see what bugs are fixed by these changes, I just want to make sure I understand why this class was added.

**Comment by SerCoach1** [comment]
@jogobom You're right about ConsoleCloseHandler, it tries killing all processes it started when terminating YoCode. I added it because I noticed that YoCode leaves 2 processes behind when terminating in the middle of execution. I wanted to make YoCode a little bit more robust :)

**Comment by jogobom** [comment]
Which 2 processes? Are they the dotnet build process and the Roslyn process? At least one of those is dotnet deliberately leaving itself running as an "optimisation".

**Comment by SerCoach1** [comment]
@jogobom The selenium driver (geckodriver.exe) and UnitConverterWebApp are left behind and that means that not only are there unwanted processes left over but the kestrel port will taken up by the previously run project.

**Pull request merged**
